export type SurahMeta = {
  number: number;
  name: string;
  arabicName: string;
  transliteration: string;
  englishLabel: string;
};

const rows = [
  ["Al-Fātiḥah", "الفاتحة", "The Opening"],
  ["Al-Baqarah", "البقرة", "The Cow"],
  ["Āl ʿImrān", "آل عمران", "Family of Imran"],
  ["An-Nisāʾ", "النساء", "The Women"],
  ["Al-Māʾidah", "المائدة", "The Table Spread"],
  ["Al-Anʿām", "الأنعام", "The Cattle"],
  ["Al-Aʿrāf", "الأعراف", "The Heights"],
  ["Al-Anfāl", "الأنفال", "The Spoils of War"],
  ["At-Tawbah", "التوبة", "The Repentance"],
  ["Yūnus", "يونس", "Jonah"],
  ["Hūd", "هود", "Hud"],
  ["Yūsuf", "يوسف", "Joseph"],
  ["Ar-Raʿd", "الرعد", "The Thunder"],
  ["Ibrāhīm", "إبراهيم", "Abraham"],
  ["Al-Ḥijr", "الحجر", "The Rocky Tract"],
  ["An-Naḥl", "النحل", "The Bee"],
  ["Al-Isrāʾ", "الإسراء", "The Night Journey"],
  ["Al-Kahf", "الكهف", "The Cave"],
  ["Maryam", "مريم", "Mary"],
  ["Ṭā-Hā", "طه", "Ta-Ha"],
  ["Al-Anbiyāʾ", "الأنبياء", "The Prophets"],
  ["Al-Ḥajj", "الحج", "The Pilgrimage"],
  ["Al-Muʾminūn", "المؤمنون", "The Believers"],
  ["An-Nūr", "النور", "The Light"],
  ["Al-Furqān", "الفرقان", "The Criterion"],
  ["Ash-Shuʿarāʾ", "الشعراء", "The Poets"],
  ["An-Naml", "النمل", "The Ant"],
  ["Al-Qaṣaṣ", "القصص", "The Stories"],
  ["Al-ʿAnkabūt", "العنكبوت", "The Spider"],
  ["Ar-Rūm", "الروم", "The Romans"],
  ["Luqmān", "لقمان", "Luqman"],
  ["As-Sajdah", "السجدة", "The Prostration"],
  ["Al-Aḥzāb", "الأحزاب", "The Combined Forces"],
  ["Sabaʾ", "سبأ", "Sheba"],
  ["Fāṭir", "فاطر", "Originator"],
  ["Yā-Sīn", "يس", "Ya-Sin"],
  ["Aṣ-Ṣāffāt", "الصافات", "Those Ranged in Ranks"],
  ["Ṣād", "ص", "Sad"],
  ["Az-Zumar", "الزمر", "The Groups"],
  ["Ghāfir", "غافر", "The Forgiver"],
  ["Fuṣṣilat", "فصلت", "Explained in Detail"],
  ["Ash-Shūrā", "الشورى", "The Consultation"],
  ["Az-Zukhruf", "الزخرف", "The Ornaments of Gold"],
  ["Ad-Dukhān", "الدخان", "The Smoke"],
  ["Al-Jāthiyah", "الجاثية", "The Crouching"],
  ["Al-Aḥqāf", "الأحقاف", "The Wind-Curved Sandhills"],
  ["Muḥammad", "محمد", "Muhammad"],
  ["Al-Fatḥ", "الفتح", "The Victory"],
  ["Al-Ḥujurāt", "الحجرات", "The Rooms"],
  ["Qāf", "ق", "Qaf"],
  ["Adh-Dhāriyāt", "الذاريات", "The Winnowing Winds"],
  ["Aṭ-Ṭūr", "الطور", "The Mount"],
  ["An-Najm", "النجم", "The Star"],
  ["Al-Qamar", "القمر", "The Moon"],
  ["Ar-Raḥmān", "الرحمن", "The Most Merciful"],
  ["Al-Wāqiʿah", "الواقعة", "The Inevitable"],
  ["Al-Ḥadīd", "الحديد", "The Iron"],
  ["Al-Mujādilah", "المجادilah", "The Pleading Woman"],
  ["Al-Ḥashr", "الحشر", "The Exile"],
  ["Al-Mumtaḥanah", "الممتحنة", "The Examined One"],
  ["Aṣ-Ṣaff", "الصف", "The صف"],
  ["Al-Jumuʿah", "الجمعة", "Friday"],
  ["Al-Munāfiqūn", "المنافقون", "The Hypocrites"],
  ["At-Taghābun", "التغابن", "Mutual Disillusion"],
  ["Aṭ-Ṭalāq", "الطلاق", "The Divorce"],
  ["At-Taḥrīm", "التحريم", "The Prohibition"],
  ["Al-Mulk", "الملك", "The Sovereignty"],
  ["Al-Qalam", "القلم", "The Pen"],
  ["Al-Ḥāqqah", "الحاقة", "The Reality"],
  ["Al-Maʿārij", "المعارج", "The Ascending Stairways"],
  ["Nūḥ", "نوح", "Noah"],
  ["Al-Jinn", "الجن", "The Jinn"],
  ["Al-Muzzammil", "المزمل", "The Enshrouded One"],
  ["Al-Muddaththir", "المدثر", "The Cloaked One"],
  ["Al-Qiyāmah", "القيامة", "The Resurrection"],
  ["Al-Insān", "الإنسان", "The Human"],
  ["Al-Mursalāt", "المرسلات", "Those Sent Forth"],
  ["An-Nabaʾ", "النبأ", "The Tidings"],
  ["An-Nāziʿāt", "النازعات", "Those Who Drag Forth"],
  ["ʿAbasa", "عبس", "He Frowned"],
  ["At-Takwīr", "التكوير", "The Overthrowing"],
  ["Al-Infiṭār", "الانفطار", "The Cleaving"],
  ["Al-Muṭaffifīn", "المطففين", "The Defrauding"],
  ["Al-Inshiqāq", "الانشقاق", "The Sundering"],
  ["Al-Burūj", "البروج", "The Mansions of the Stars"],
  ["Aṭ-Ṭāriq", "الطارق", "The Nightcomer"],
  ["Al-Aʿlā", "الأعلى", "The Most High"],
  ["Al-Ghāshiyah", "الغاشية", "The Overwhelming"],
  ["Al-Fajr", "الفجر", "The Dawn"],
  ["Al-Balad", "البلد", "The City"],
  ["Ash-Shams", "الشمس", "The Sun"],
  ["Al-Layl", "الليل", "The Night"],
  ["Aḍ-Ḍuḥā", "الضحى", "The Morning Hours"],
  ["Ash-Sharḥ", "الشرح", "The Relief"],
  ["At-Tīn", "التين", "The Fig"],
  ["Al-ʿAlaq", "العلق", "The Clot"],
  ["Al-Qadr", "القدر", "The Power"],
  ["Al-Bayyinah", "البينة", "The Clear Proof"],
  ["Az-Zalzalah", "الزلزلة", "The Earthquake"],
  ["Al-ʿĀdiyāt", "العاديات", "The Courser"],
  ["Al-Qāriʿah", "القارعة", "The Striking Hour"],
  ["At-Takāthur", "التكاثر", "The Rivalry in World Increase"],
  ["Al-ʿAṣr", "العصر", "The Declining Day"],
  ["Al-Humazah", "الهمزة", "The Traducer"],
  ["Al-Fīl", "الفيل", "The Elephant"],
  ["Quraysh", "قريش", "Quraysh"],
  ["Al-Māʿūn", "الماعون", "Small Kindnesses"],
  ["Al-Kawthar", "الكوثر", "Abundance"],
  ["Al-Kāfirūn", "الكافرون", "The Disbelievers"],
  ["An-Naṣr", "النصر", "The Divine Help"],
  ["Al-Masad", "المسد", "The Palm Fibre"],
  ["Al-Ikhlāṣ", "الإخلاص", "Sincerity"],
  ["Al-Falaq", "الفلق", "The Daybreak"],
  ["An-Nās", "الناس", "Humankind"],
] as const;

export const surahMeta: SurahMeta[] = rows.map(
  ([transliteration, arabicName, englishLabel], index) => ({
    number: index + 1,
    name: transliteration,
    arabicName,
    transliteration,
    englishLabel,
  }),
);
